const Order  =  require('../models/order');
const nodemailer = require('nodemailer');


function sendMail(data){
    var transport = nodemailer.createTransport({
        host: process.env.EMAIL_HOST,
        port: process.env.EMAIL_PORT,
        auth: {
          user: process.env.EMAIL_USER, //generated by Mailtrap
          pass: process.env.EMAIL_PASSWORD //generated by Mailtrap
        }
      });

      var mailOptions = {
        from: process.env.EMAIL_SENDER,
       /*  to: 'user1@example.com, user2@example.com', */
       to:data.email,
        subject: 'Nice Nodemailer test',
        text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
        html: `<b>Hey there! </b><br> This is our first message sent with Nodemailer
       order details ${data}
        `

    };

    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
});




}

exports.createOrder = async (req,res,next) =>{

    console.log(req.body);
    
    const fullName = req.body.fullName;
    const email = req.body.email;
    const phoneNumber = req.body.phoneNumber;
    const theatreName = req.body.theatreName;
    const screenDate = req.body.screenDate;
    const screenFromTime = req.body.screenFromTime;
    const screenToTime = req.body.screenToTime;
    const price = req.body.price;
    const numberOfSeats = req.body.numberOfSeats;

    const order = new Order({
        fullName:fullName,
        email:email,
        phoneNumber:phoneNumber,
        theatreName:theatreName,
        screenDate:screenDate,
        screenFromTime:screenFromTime,
        screenToTime:screenToTime,
        price:price,
        numberOfSeats:numberOfSeats
    });

    try {
        let resultOrder  =  await order.save();

        sendMail(resultOrder);

        res.status(201).json({
            message: 'Order created successfully',
            order: resultOrder,
          });
        
    } catch (err) {
        if (!err.statusCode) {
            err.statusCode = 500;
          }
        next(err);
    }



}










