const nodemailer = require('nodemailer');

const Order  =  require('../models/order');
const Theatre = require('../models/theatre');

const { validationResult} =  require('express-validator');


function sendMail(data){
    var transport = nodemailer.createTransport({
        host: process.env.EMAIL_HOST,
        port: process.env.EMAIL_PORT,
        auth: {
          user: process.env.EMAIL_USER, //generated by Mailtrap
          pass: process.env.EMAIL_PASSWORD //generated by Mailtrap
        }
      });

      var mailOptions = {
        from: process.env.EMAIL_SENDER,
       /*  to: 'user1@example.com, user2@example.com', */
       to:data.email,
        subject: 'Nice Nodemailer test',
        text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
        html: `<b>Hey there! </b><br> This is our first message sent with Nodemailer
       order details ${data}
        `

    };

    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
});




}

exports.createOrder = async (req,res,next) =>{
    



    try {

        const errors =  validationResult(req);
        if(!errors.isEmpty()){
            const error  =  new Error('Validation failed');
            error.statusCode  = 422;
            error.data  =  errors.array();
            throw error;
        }

       // console.log(req.body);
    
        const fullName = req.body.fullName;
        const email = req.body.email;
        const phoneNumber = req.body.phoneNumber;
        const theatreName = req.body.theatreName;
        let screenDate = req.body.screenDate;
   
        const screenFromTime = req.body.screenFromTime;
        const screenToTime = req.body.screenToTime;
        const price = req.body.price;
        const numberOfSeats = req.body.numberOfSeats;
        const slotName  =  req.body.slotName;
    
        const order = new Order({
            fullName:fullName,
            email:email,
            phoneNumber:phoneNumber,
            theatreName:theatreName,
            screenDate:screenDate,
            screenFromTime:screenFromTime,
            screenToTime:screenToTime,
            price:price,
            numberOfSeats:numberOfSeats
        });
    
        console.log(order.screenDate);


        let resultTheatre = await Theatre.findOne({theatreName:theatreName,screenDate:screenDate});
     //  console.log(await Theatre.find({theatreName:theatreName,screenDate:screenDate}));
        console.log("obtained theatre " + resultTheatre)
         if(resultTheatre.isMorning === true && slotName === "MORNING"){
            resultTheatre.isMorning = false;
            await resultTheatre.save();
        }
       else if(resultTheatre.isAfternoon === true && slotName === "AFTERNOON"){
            resultTheatre.isAfternoon = false;
            await resultTheatre.save();
        }
       else if(resultTheatre.isEvening === true && slotName === "EVENING"){
            resultTheatre.isEvening = false;
            await resultTheatre.save();
        }
        else if(resultTheatre.isNight === true && slotName === "NIGHT"){
            resultTheatre.isEvening = false;
            await resultTheatre.save();
        }
        else{
         return res.status(400).json({
                message :"Please enter the input in correct formate"
            });
        } 
        
        let resultOrder  =  await order.save();

        sendMail(resultOrder);

        res.status(201).json({
            message: 'Order created successfully',
            order: resultOrder,
          });
        
    } catch (err) {
        if (!err.statusCode) {
            err.statusCode = 500;
          }
        next(err);
    }



}


exports.availableSlots  =  async (req,res,next) => {
  // date = new Date(date);
   // let screenDate = date.toISOString().slice(0,10);
    //screenDate = date.slice(0,10);
   // console.log("converted date " + screenDate);

    // TODO : date validation (date must be greater than todays date)

    try {

        const errors =  validationResult(req);
        if(!errors.isEmpty()){
            const error  =  new Error('Validation failed');
            error.statusCode  = 422;
            error.data  =  errors.array();
            throw error;
        }
    
        console.log(req.query);
    
        const theatreName = req.query.theatreName;
        //const screenDate  =  req.query.screenDate;
    
        let screenDate = req.query.screenDate;
    
        console.log("received date " + screenDate);
        
        const theatre = await Theatre.findOne({theatreName:theatreName,screenDate:screenDate});
        
        console.log("found theatre " + theatre);
        if(theatre === null){
            const createdtheatre = new Theatre({
                theatreName : theatreName,
                screenDate:screenDate
            });

         let resultTheatre  =  await createdtheatre.save();

         res.status(200).json({
            message:"available slots",
            theatre:resultTheatre
         })

        }
        else{
            res.status(200).json({
                message: "available slots",
                theatre: theatre
            });
        }

    } catch (err) {
        if (!err.statusCode) {
            err.statusCode = 500;
          }
        next(err);
    }


}










